#!/usr/bin/env node
// Build: sync <head> metadata from assets/js/config.js into index.html, then copy the
// static site into dist/ with generated robots.txt and sitemap.xml. No dependencies.
//
//   node scripts/build.mjs           # sync meta + build dist/
//   node scripts/build.mjs --check   # exit 1 if index.html meta is out of sync (CI)
import { readFile, writeFile, rm, mkdir, cp } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { CONFIG, contactLinks } from '../assets/js/config.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');
const START = '<!-- META:START (generated by scripts/build.mjs from assets/js/config.js — edit config.js, not this block) -->';
const END = '<!-- META:END -->';

const escAttr = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export function metaBlock(cfg = CONFIG) {
  const site = cfg.SITE_URL.endsWith('/') ? cfg.SITE_URL : `${cfg.SITE_URL}/`;
  const title = `${cfg.name} — ${cfg.title} · Agentic & Generative AI`;
  const image = `${site}assets/img/og-image.png`;
  const links = contactLinks(cfg);
  const person = {
    '@context': 'https://schema.org',
    '@type': 'Person',
    name: cfg.name,
    jobTitle: cfg.title,
    description: cfg.description,
    url: site,
    knowsAbout: ['Agentic AI', 'Generative AI', 'Retrieval-Augmented Generation', 'LLM Engineering', 'Enterprise AI Architecture', 'Model Context Protocol', 'Machine Learning'],
  };
  const sameAs = [links.github.href, links.linkedin.href].filter(Boolean);
  if (sameAs.length) person.sameAs = sameAs;
  // Email is intentionally NOT included in structured data to limit scraping.
  const jsonLd = JSON.stringify(person).replace(/</g, '\\u003c');
  return [
    START,
    `<title>${escAttr(title)}</title>`,
    `<meta name="description" content="${escAttr(cfg.description)}">`,
    `<link rel="canonical" href="${escAttr(site)}">`,
    '<meta property="og:type" content="profile">',
    `<meta property="og:title" content="${escAttr(title)}">`,
    `<meta property="og:description" content="${escAttr(cfg.description)}">`,
    `<meta property="og:url" content="${escAttr(site)}">`,
    `<meta property="og:image" content="${escAttr(image)}">`,
    '<meta property="og:image:width" content="1200">',
    '<meta property="og:image:height" content="630">',
    `<meta property="og:image:alt" content="${escAttr(`${cfg.name} — ${cfg.title}. ${cfg.tagline}`)}">`,
    '<meta name="twitter:card" content="summary_large_image">',
    `<meta name="twitter:title" content="${escAttr(title)}">`,
    `<meta name="twitter:description" content="${escAttr(cfg.description)}">`,
    `<meta name="twitter:image" content="${escAttr(image)}">`,
    `<script type="application/ld+json">${jsonLd}</script>`,
    END,
  ].join('\n');
}

function syncHtml(html) {
  const a = html.indexOf(START);
  const b = html.indexOf(END);
  if (a === -1 || b === -1) throw new Error('META markers not found in index.html');
  return html.slice(0, a) + metaBlock() + html.slice(b + END.length);
}

async function main() {
  const indexPath = path.join(ROOT, 'index.html');
  const html = await readFile(indexPath, 'utf8');
  const synced = syncHtml(html);

  if (process.argv.includes('--check')) {
    if (synced !== html) {
      console.error('✗ index.html <head> metadata is out of sync with config.js. Run: node scripts/build.mjs');
      process.exit(1);
    }
    console.log('✓ index.html metadata in sync with config.js');
    return;
  }

  if (synced !== html) {
    await writeFile(indexPath, synced);
    console.log('• synced <head> metadata from config.js');
  }

  const site = new URL(CONFIG.SITE_URL);
  const base = site.pathname.endsWith('/') ? site.pathname : `${site.pathname}/`;

  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });
  await cp(path.join(ROOT, 'assets'), path.join(DIST, 'assets'), { recursive: true });
  await writeFile(path.join(DIST, 'index.html'), synced);
  // 404 is served from arbitrary paths, so its links must be absolute to the site base.
  const notFound = (await readFile(path.join(ROOT, '404.html'), 'utf8'))
    .replaceAll('href="./"', `href="${base}"`)
    .replaceAll('href="assets/', `href="${base}assets/`);
  await writeFile(path.join(DIST, '404.html'), notFound);
  await writeFile(path.join(DIST, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${new URL('sitemap.xml', CONFIG.SITE_URL).href}\n`);
  await writeFile(
    path.join(DIST, 'sitemap.xml'),
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>${CONFIG.SITE_URL}</loc><lastmod>${new Date().toISOString().slice(0, 10)}</lastmod></url>\n</urlset>\n`,
  );
  await writeFile(path.join(DIST, '.nojekyll'), '');
  console.log(`✓ built dist/ (base path ${base})`);
}

main().catch((err) => { console.error(err); process.exit(1); });
