"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 18:43:41.646845
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('node', sa.String(length=40), nullable=True),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('generation_mode', sa.String(length=16), nullable=True),
    sa.Column('connector_mode', sa.String(length=16), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.Column('generation_mode', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('authority', sa.String(length=32), nullable=False),
    sa.Column('product', sa.String(length=64), nullable=False),
    sa.Column('tenant_scope', sa.String(length=64), nullable=False),
    sa.Column('allowed_roles', sa.JSON(), nullable=False),
    sa.Column('effective_date', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulated_external_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('system', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system', 'idempotency_key', name='uq_sim_ext_idem')
    )
    with op.batch_alter_table('simulated_external_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulated_external_records_case_id'), ['case_id'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('contact_phone', sa.String(length=40), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('network_assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('postal_area', sa.String(length=16), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['network_assets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_assets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('account_segments', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('segment', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('service_address', sa.String(length=300), nullable=False),
    sa.Column('postal_area', sa.String(length=16), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('estimated_restoration_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status_history', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['network_assets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('product', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('access_technology', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('support_interactions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('actions_taken', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('author_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_interactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_interactions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('complaint_text', sa.Text(), nullable=False),
    sa.Column('reported_symptoms', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('linked_incident_id', sa.String(length=64), nullable=True),
    sa.Column('current_recommendation_id', sa.String(length=64), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=False),
    sa.Column('workflow_thread_id', sa.String(length=96), nullable=True),
    sa.Column('active_job', sa.String(length=64), nullable=True),
    sa.Column('simulation_profile', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('diagnostic_samples',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('collected_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('link_state', sa.String(length=16), nullable=False),
    sa.Column('loss_of_signal_events', sa.Integer(), nullable=False),
    sa.Column('link_retrains', sa.Integer(), nullable=False),
    sa.Column('packet_loss_pct', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('snr_margin_db', sa.Float(), nullable=True),
    sa.Column('crc_errors', sa.Integer(), nullable=False),
    sa.Column('cpe_uptime_s', sa.Integer(), nullable=True),
    sa.Column('cpe_unexpected_reboots', sa.Integer(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('simulated_post_action', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostic_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostic_samples_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_samples_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_samples_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('equipment',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('firmware', sa.String(length=32), nullable=False),
    sa.Column('installed_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('service_asset_mappings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=False),
    sa.Column('valid_from', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_to', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['network_assets.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_asset_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_asset_mappings_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_asset_mappings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('case_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('generation_mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_messages_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_messages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('evidence_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('bundle', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_snapshots_case_id'), ['case_id'], unique=False)

    op.create_table('evidence_references',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=96), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('authority', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('freshness', sa.String(length=16), nullable=False),
    sa.Column('supports', sa.JSON(), nullable=False),
    sa.Column('opposes', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('retrieved_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['evidence_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_references_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_references_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('hypotheses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('sufficiency', sa.String(length=16), nullable=False),
    sa.Column('supporting_refs', sa.JSON(), nullable=False),
    sa.Column('opposing_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['evidence_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hypotheses_case_id'), ['case_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('uncertainty', sa.Text(), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('approval_requirement', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('policy_decision', sa.JSON(), nullable=False),
    sa.Column('prior_interventions', sa.JSON(), nullable=False),
    sa.Column('refused_requests', sa.JSON(), nullable=False),
    sa.Column('alternatives', sa.JSON(), nullable=False),
    sa.Column('proposed_by', sa.String(length=64), nullable=False),
    sa.Column('generation_mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['evidence_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_case_id'), ['case_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('recommendation_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('evidence_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('requested_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('required_roles', sa.JSON(), nullable=False),
    sa.Column('separation_of_duties', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('consumed_by_execution_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)

    op.create_table('action_executions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('executed_by', sa.String(length=64), nullable=False),
    sa.Column('connector', sa.String(length=64), nullable=False),
    sa.Column('connector_mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('external_ref', sa.String(length=96), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_id'),
    sa.UniqueConstraint('case_id', 'idempotency_key', name='uq_exec_idem')
    )
    with op.batch_alter_table('action_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_executions_case_id'), ['case_id'], unique=False)

    op.create_table('recovery_observations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('checked_by', sa.String(length=64), nullable=False),
    sa.Column('checked_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('window_start', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('window_end', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sample_ids', sa.JSON(), nullable=False),
    sa.Column('healthy_samples', sa.Integer(), nullable=False),
    sa.Column('unhealthy_samples', sa.Integer(), nullable=False),
    sa.Column('required_samples', sa.Integer(), nullable=False),
    sa.Column('customer_report_conflict', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('simulation_time', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['action_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_observations_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_observations_case_id'))

    op.drop_table('recovery_observations')
    with op.batch_alter_table('action_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_executions_case_id'))

    op.drop_table('action_executions')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_case_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_case_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hypotheses_case_id'))

    op.drop_table('hypotheses')
    with op.batch_alter_table('evidence_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_references_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_references_case_id'))

    op.drop_table('evidence_references')
    with op.batch_alter_table('evidence_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_snapshots_case_id'))

    op.drop_table('evidence_snapshots')
    with op.batch_alter_table('case_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_messages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_case_messages_case_id'))

    op.drop_table('case_messages')
    with op.batch_alter_table('service_asset_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_asset_mappings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_service_asset_mappings_service_id'))

    op.drop_table('service_asset_mappings')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_service_id'))

    op.drop_table('equipment')
    with op.batch_alter_table('diagnostic_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostic_samples_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_samples_service_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_samples_collected_at'))

    op.drop_table('diagnostic_samples')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cases_status'))

    op.drop_table('cases')
    with op.batch_alter_table('support_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_interactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_support_interactions_account_id'))

    op.drop_table('support_interactions')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_tenant_id'))

    op.drop_table('services')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_tenant_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_tenant_id'))

    op.drop_table('accounts')
    op.drop_table('users')
    with op.batch_alter_table('network_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_assets_tenant_id'))

    op.drop_table('network_assets')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_id'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_tenant_id'))

    op.drop_table('customers')
    op.drop_table('tenants')
    with op.batch_alter_table('simulated_external_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulated_external_records_case_id'))

    op.drop_table('simulated_external_records')
    op.drop_table('knowledge_documents')
    op.drop_table('evaluation_runs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_case_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
