"""initial schema

Revision ID: 2d332e8914f0
Revises: 
Create Date: 2026-10-11 02:55:20.743690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d332e8914f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_invocations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('language_mode', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_id', sa.String(length=80), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('price_config', sa.String(length=40), nullable=True),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_invocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_invocations_change_id'), ['change_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('version_refs', sa.JSON(), nullable=False),
    sa.Column('input_refs', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=80), nullable=False),
    sa.Column('hash', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_change_id'), ['change_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('code_revisions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('author_user_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('diff_digest', sa.String(length=80), nullable=False),
    sa.Column('requirement_refs', sa.JSON(), nullable=False),
    sa.Column('test_refs', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copilot_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copilot_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_messages_change_id'), ['change_id'], unique=False)

    op.create_table('dataset_consent_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('sample_id', sa.String(length=40), nullable=False),
    sa.Column('consent_status', sa.String(length=20), nullable=False),
    sa.Column('permitted_use', sa.JSON(), nullable=False),
    sa.Column('retention_until', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_consent_records_sample_id'), ['sample_id'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('devices_covered', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('request_digest', sa.String(length=80), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('image_uploads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('consent_text_version', sa.String(length=40), nullable=False),
    sa.Column('training_consent', sa.Boolean(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=30), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('metadata_stripped', sa.JSON(), nullable=False),
    sa.Column('storage_inventory', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deletion_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete_after', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('artifact_digest', sa.String(length=80), nullable=False),
    sa.Column('artifact_uri', sa.String(length=300), nullable=False),
    sa.Column('preprocessing', sa.JSON(), nullable=False),
    sa.Column('catalogue_version', sa.String(length=40), nullable=False),
    sa.Column('code_revision_id', sa.String(length=100), nullable=False),
    sa.Column('lighting_profile_map_id', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('pending_nodes', sa.JSON(), nullable=False),
    sa.Column('interrupt', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_checkpoints_change_id'), ['change_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_checkpoints_thread_id'), ['thread_id'], unique=False)

    op.create_table('dataset_records',
    sa.Column('sample_id', sa.String(length=40), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=100), nullable=False),
    sa.Column('split', sa.String(length=20), nullable=False),
    sa.Column('tone_stratum', sa.String(length=20), nullable=False),
    sa.Column('lighting_category', sa.String(length=40), nullable=False),
    sa.Column('device_category', sa.String(length=20), nullable=False),
    sa.Column('expected_shade_id', sa.String(length=20), nullable=False),
    sa.Column('label_provenance', sa.Text(), nullable=False),
    sa.Column('consent_record_id', sa.String(length=40), nullable=False),
    sa.Column('image_quality', sa.String(length=10), nullable=False),
    sa.Column('grouping_protocol', sa.Text(), nullable=False),
    sa.Column('image_ref', sa.String(length=200), nullable=False),
    sa.Column('declared_eligible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    with op.batch_alter_table('dataset_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_records_dataset_version_id'), ['dataset_version_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('persona', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_requirement_version_id', sa.String(length=64), nullable=True),
    sa.Column('baseline_model_id', sa.String(length=100), nullable=False),
    sa.Column('candidate_model_id', sa.String(length=100), nullable=True),
    sa.Column('code_revision_id', sa.String(length=100), nullable=True),
    sa.Column('dataset_snapshot_id', sa.String(length=100), nullable=True),
    sa.Column('evaluation_config_id', sa.String(length=100), nullable=True),
    sa.Column('latest_evaluation_run_id', sa.String(length=64), nullable=True),
    sa.Column('impact_accepted', sa.Boolean(), nullable=False),
    sa.Column('deployment_target', sa.String(length=100), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_requests_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('approver_id', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('binding', sa.JSON(), nullable=False),
    sa.Column('binding_digest', sa.String(length=80), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by', sa.String(length=64), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_change_id'), ['change_id'], unique=False)

    op.create_table('clarifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('owner_role', sa.String(length=64), nullable=False),
    sa.Column('suggested_answer', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('structured_answer', sa.JSON(), nullable=True),
    sa.Column('answered_by', sa.String(length=64), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clarifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clarifications_change_id'), ['change_id'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('baseline_model_id', sa.String(length=100), nullable=False),
    sa.Column('candidate_model_id', sa.String(length=100), nullable=False),
    sa.Column('candidate_artifact_digest', sa.String(length=80), nullable=True),
    sa.Column('baseline_artifact_digest', sa.String(length=80), nullable=True),
    sa.Column('code_revision_id', sa.String(length=100), nullable=True),
    sa.Column('dataset_snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('dataset_digest', sa.String(length=80), nullable=True),
    sa.Column('evaluation_config_id', sa.String(length=100), nullable=False),
    sa.Column('evaluation_config_digest', sa.String(length=80), nullable=True),
    sa.Column('policy_version', sa.String(length=40), nullable=True),
    sa.Column('requirement_version_id', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('test_set_evaluation_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_runs_change_id'), ['change_id'], unique=False)

    op.create_table('evidence_references',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_version', sa.String(length=30), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_by', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_references_change_id'), ['change_id'], unique=False)

    op.create_table('gate_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('context', sa.String(length=30), nullable=False),
    sa.Column('gate_id', sa.String(length=64), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('observed', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_role', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gate_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gate_decisions_change_id'), ['change_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gate_decisions_run_id'), ['run_id'], unique=False)

    op.create_table('impact_assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('requirement_version_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('accepted_by', sa.String(length=64), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impact_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impact_assessments_change_id'), ['change_id'], unique=False)

    op.create_table('releases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('artifact_digest', sa.String(length=80), nullable=False),
    sa.Column('previous_model_id', sa.String(length=100), nullable=False),
    sa.Column('previous_artifact_digest', sa.String(length=80), nullable=False),
    sa.Column('deployment_target', sa.String(length=100), nullable=False),
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_releases_change_id'), ['change_id'], unique=False)

    op.create_table('requirement_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_id', 'version')
    )
    with op.batch_alter_table('requirement_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_versions_change_id'), ['change_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('binding', sa.JSON(), nullable=False),
    sa.Column('binding_digest', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_change_id'), ['change_id'], unique=False)

    op.create_table('acceptance_criteria',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('requirement_version_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=True),
    sa.Column('gate_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['requirement_version_id'], ['requirement_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acceptance_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acceptance_criteria_requirement_version_id'), ['requirement_version_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('release_id', sa.String(length=64), nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('observed', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('investigation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_change_id'), ['change_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_release_id'), ['release_id'], unique=False)

    op.create_table('metric_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('model_role', sa.String(length=20), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_results_run_id'), ['run_id'], unique=False)

    op.create_table('monitoring_windows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('release_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('allocation_pct', sa.Integer(), nullable=False),
    sa.Column('simulated_sessions', sa.Integer(), nullable=False),
    sa.Column('exposures', sa.Integer(), nullable=False),
    sa.Column('labelled', sa.Integer(), nullable=False),
    sa.Column('cohorts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('release_id', 'index')
    )
    with op.batch_alter_table('monitoring_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_windows_release_id'), ['release_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('sample_id', sa.String(length=40), nullable=False),
    sa.Column('top3', sa.JSON(), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('ix_pred_run_model', ['run_id', 'model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_run_id'), ['run_id'], unique=False)

    op.create_table('rollback_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('release_id', sa.String(length=64), nullable=False),
    sa.Column('change_id', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('alert_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('target_model_id', sa.String(length=100), nullable=False),
    sa.Column('compatibility', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rollback_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rollback_records_release_id'), ['release_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollback_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollback_records_release_id'))

    op.drop_table('rollback_records')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_run_id'))
        batch_op.drop_index('ix_pred_run_model')

    op.drop_table('predictions')
    with op.batch_alter_table('monitoring_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_windows_release_id'))

    op.drop_table('monitoring_windows')
    with op.batch_alter_table('metric_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_results_run_id'))

    op.drop_table('metric_results')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_release_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_change_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('acceptance_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acceptance_criteria_requirement_version_id'))

    op.drop_table('acceptance_criteria')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_change_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('requirement_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_versions_change_id'))

    op.drop_table('requirement_versions')
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_change_id'))

    op.drop_table('releases')
    with op.batch_alter_table('impact_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impact_assessments_change_id'))

    op.drop_table('impact_assessments')
    with op.batch_alter_table('gate_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gate_decisions_run_id'))
        batch_op.drop_index(batch_op.f('ix_gate_decisions_change_id'))

    op.drop_table('gate_decisions')
    with op.batch_alter_table('evidence_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_references_change_id'))

    op.drop_table('evidence_references')
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_change_id'))

    op.drop_table('evaluation_runs')
    with op.batch_alter_table('clarifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clarifications_change_id'))

    op.drop_table('clarifications')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_change_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_requests_tenant_id'))

    op.drop_table('change_requests')
    op.drop_table('users')
    with op.batch_alter_table('dataset_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_records_dataset_version_id'))

    op.drop_table('dataset_records')
    with op.batch_alter_table('workflow_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_checkpoints_thread_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_checkpoints_change_id'))

    op.drop_table('workflow_checkpoints')
    op.drop_table('tenants')
    op.drop_table('model_versions')
    op.drop_table('image_uploads')
    op.drop_table('idempotency_records')
    op.drop_table('dataset_versions')
    with op.batch_alter_table('dataset_consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_consent_records_sample_id'))

    op.drop_table('dataset_consent_records')
    with op.batch_alter_table('copilot_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_messages_change_id'))

    op.drop_table('copilot_messages')
    op.drop_table('code_revisions')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_change_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('agent_invocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_invocations_change_id'))

    op.drop_table('agent_invocations')
    # ### end Alembic commands ###
